/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.interfaz;

import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.idao.ITelefonoDAO;
import ec.edu.ups.interfaz.IngresoTelefono;
import javax.swing.JOptionPane;

/**
 *
 * @author tano
 */
public class InicioSesion extends javax.swing.JFrame {

    private ControladorUsuario controladorUsuario;
    private ITelefonoDAO dao;
    private IngresoTelefono it;
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(ControladorUsuario controladorUsuario, ITelefonoDAO dao) {
	initComponents();
	this.dao = dao;
	this.controladorUsuario = controladorUsuario;
	this.setTitle("Inicio de Sesión");
	this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsr = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUsr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsr.setText("Usuario");

        lblPass.setText("Contraseña");

        txtUsr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsr)
                            .addComponent(lblPass))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(pass)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsr)
                    .addComponent(txtUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*if(controladorUsuario.iniciarSesionVentana(txtUsr.getText(), new String(pass.getPassword()))){
	//if(txtUsr.getText().equals("admin")){
	    //String str = new String(pass.getPassword());
	    //if(str.equals("1234"))
		if(it == null)
		    it = new IngresoTelefono(controladorUsuario, dao);
		it.setVisible(true);
	}
	else
	    JOptionPane.showMessageDialog(this, "Usuario o contraseña erroneos", "Error", JOptionPane.ERROR_MESSAGE);
	*/
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsr;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txtUsr;
    // End of variables declaration//GEN-END:variables
}
