package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDAO;
import ec.edu.ups.dao.UsuarioDAO;
import ec.edu.ups.idao.ITelefonoDAO;
import ec.edu.ups.idao.IUsuarioDAO;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class VentanaPrincipal extends javax.swing.JFrame {

    //vista
    private VentanaIniciarSesion iniciarSesion;
    private VentanaRegistrarUsuario registrarUsuario;
    private VentanaGestionTelefono gestionTelefono;
    private VentanaGestionUsuario gestionUsuario;
    private VentanaBuscarTelefono buscarTelefono;
    //daos
    private IUsuarioDAO usuarioDAO;
    private ITelefonoDAO telefonoDAO;
    //controladores
    private ControladorUsuario controladorUsuario;
    private ControladorTelefono controladorTelefono;
    //Localización
    private Locale localizacion;
    private ResourceBundle mensajes;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
	initComponents();
	this.setSize(800, 600);
	menuGestion.setVisible(false);
	cerrarMenuItem.setVisible(false);
	
	usuarioDAO = new UsuarioDAO();
	
	controladorUsuario = new ControladorUsuario(usuarioDAO);
	telefonoDAO = new TelefonoDAO(controladorUsuario);
	controladorTelefono = new ControladorTelefono(telefonoDAO, controladorUsuario);
	
	controladorUsuario.registrar("0104760517",
				    "sebastian",
				    "toledo",
				    "tano",
				    "12345678");
	/*controladorUsuario.registrar("0105698123",
				    "pepito",
				    "perez",
				    "pepito001",
				    "54321");
	controladorUsuario.iniciarSesion("mtoledot1","12345");
	controladorTelefono.registrar(controladorTelefono.cantidadTelefonos(),
					"(+593)-0-986-5212",
					"Móvil",
					"Claro");
	controladorTelefono.registrar(controladorTelefono.cantidadTelefonos(),
					"(+593)-0-983-6985",
					"Móvil",
					"CNT");
	controladorUsuario.iniciarSesion("pepito001","54321");
	controladorTelefono.registrar(controladorTelefono.cantidadTelefonos(),
					"(+593)-0-996-5432",
					"Móvil",
					"Movistar");*/
	
	localizacion = new Locale("es","EC");
	mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", localizacion);
	
	iniciarSesion = new VentanaIniciarSesion(controladorUsuario, this, localizacion, mensajes);
	registrarUsuario = new VentanaRegistrarUsuario(controladorUsuario, localizacion, mensajes);
	gestionTelefono = new VentanaGestionTelefono(controladorTelefono, controladorUsuario, localizacion, mensajes);
	gestionUsuario = new VentanaGestionUsuario(controladorUsuario);
	buscarTelefono = new VentanaBuscarTelefono(controladorUsuario, controladorTelefono);
	//localizacion = Locale.getDefault();
	
	cambiarIdioma();
    }
    
    public void cambiarIdioma(){
	menuInicio.setText(mensajes.getString("menuInicio"));
	menuGestion.setText(mensajes.getString("menuGestion"));
	menuIdioma.setText(mensajes.getString("menuIdioma"));
	cerrarMenuItem.setText(mensajes.getString("cerrarMenuItem"));
	exitMenuItem.setText(mensajes.getString("exitMenuItem"));
	iniciarMenuItem.setText(mensajes.getString("iniciarMenuItem"));
	listarTlfMenuItem.setText(mensajes.getString("listarTlfMenuItem"));
	menuItemEspañol.setText(mensajes.getString("menuItemEspañol"));
	menuItemInglés.setText(mensajes.getString("menuItemInglés"));
	registrarUsrMenuItem.setText(mensajes.getString("registrarUsrMenuItem"));
	telefonoMenuItem.setText(mensajes.getString("telefonoMenuItem"));
	usuarioMenuItem.setText(mensajes.getString("usuarioMenuItem"));
	iniciarSesion.cambiarIdioma(localizacion, mensajes);
	registrarUsuario.cambiarIdioma(localizacion, mensajes);
	gestionTelefono.cambiarIdioma(localizacion, mensajes);
    }
    
    public JMenu getMenuAgenda(){
	return menuGestion;
    }
    
    public JMenuItem getMenuItemCerrar(){
	return cerrarMenuItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        iniciarMenuItem = new javax.swing.JMenuItem();
        registrarUsrMenuItem = new javax.swing.JMenuItem();
        listarTlfMenuItem = new javax.swing.JMenuItem();
        cerrarMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        telefonoMenuItem = new javax.swing.JMenuItem();
        usuarioMenuItem = new javax.swing.JMenuItem();
        menuIdioma = new javax.swing.JMenu();
        menuItemEspañol = new javax.swing.JMenuItem();
        menuItemInglés = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuInicio.setMnemonic('f');
        menuInicio.setText("Inicio");

        iniciarMenuItem.setMnemonic('o');
        iniciarMenuItem.setText("Iniciar Sesión");
        iniciarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(iniciarMenuItem);

        registrarUsrMenuItem.setMnemonic('s');
        registrarUsrMenuItem.setText("Registrar Usuario");
        registrarUsrMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsrMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(registrarUsrMenuItem);

        listarTlfMenuItem.setText("Listar Teléfonos");
        listarTlfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarTlfMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(listarTlfMenuItem);

        cerrarMenuItem.setText("Cerrar Sesión");
        cerrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(cerrarMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(exitMenuItem);

        menuBar.add(menuInicio);

        menuGestion.setText("Agenda");

        telefonoMenuItem.setText("Telefonos");
        telefonoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoMenuItemActionPerformed(evt);
            }
        });
        menuGestion.add(telefonoMenuItem);

        usuarioMenuItem.setText("Usuarios");
        usuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuItemActionPerformed(evt);
            }
        });
        menuGestion.add(usuarioMenuItem);

        menuBar.add(menuGestion);

        menuIdioma.setText("Idioma");

        menuItemEspañol.setText("Español");
        menuItemEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspañolActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemEspañol);

        menuItemInglés.setText("Inglés");
        menuItemInglés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInglésActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemInglés);

        menuBar.add(menuIdioma);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
	System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void iniciarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarMenuItemActionPerformed
        desktopPane.add(iniciarSesion);
	iniciarSesion.setVisible(true);
    }//GEN-LAST:event_iniciarMenuItemActionPerformed

    private void registrarUsrMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsrMenuItemActionPerformed
        desktopPane.add(registrarUsuario);
	registrarUsuario.setVisible(true);
    }//GEN-LAST:event_registrarUsrMenuItemActionPerformed

    private void telefonoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoMenuItemActionPerformed
        desktopPane.add(gestionTelefono);
	gestionTelefono.setVisible(true);
    }//GEN-LAST:event_telefonoMenuItemActionPerformed

    private void usuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuItemActionPerformed
        desktopPane.add(gestionUsuario);
	gestionUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioMenuItemActionPerformed

    private void listarTlfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarTlfMenuItemActionPerformed
        desktopPane.add(buscarTelefono);
	buscarTelefono.setVisible(true);
    }//GEN-LAST:event_listarTlfMenuItemActionPerformed

    private void cerrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarMenuItemActionPerformed
	iniciarSesion.dispose();
	registrarUsuario.dispose();
	gestionTelefono.dispose();
	gestionUsuario.dispose();
	buscarTelefono.dispose();
	menuGestion.setVisible(false);
	cerrarMenuItem.setVisible(false);
	controladorUsuario.cerrarSesion();
    }//GEN-LAST:event_cerrarMenuItemActionPerformed

    private void menuItemEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspañolActionPerformed
        localizacion = new Locale("es","EC");
	mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", localizacion);
	cambiarIdioma();
    }//GEN-LAST:event_menuItemEspañolActionPerformed

    private void menuItemInglésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInglésActionPerformed
        localizacion = new Locale("en","UK");
	mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", localizacion);
	cambiarIdioma();
    }//GEN-LAST:event_menuItemInglésActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new VentanaPrincipal().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem iniciarMenuItem;
    private javax.swing.JMenuItem listarTlfMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuItemEspañol;
    private javax.swing.JMenuItem menuItemInglés;
    private javax.swing.JMenuItem registrarUsrMenuItem;
    private javax.swing.JMenuItem telefonoMenuItem;
    private javax.swing.JMenuItem usuarioMenuItem;
    // End of variables declaration//GEN-END:variables

}
